/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superdetodosa;

import java.awt.Graphics;
import java.awt.Image;
import superdetodosa.PorRubro;
import java.util.TreeSet;
import javax.swing.ImageIcon;
import superdetodosa.modelo.Producto;

/**
 *
 * @author Celia
 */
public class Menu extends javax.swing.JFrame {
public static TreeSet<Producto> productos= new TreeSet<>();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono= new ImageIcon(getClass().getResource("iconos/transparente.png"));
        Image miImagen= icono.getImage();
        escritorio2 = new javax.swing.escritorio2(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen,0,0, getWidth(), getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdministracion = new javax.swing.JMenu();
        jmiGestion = new javax.swing.JMenuItem();
        jmConsulta = new javax.swing.JMenu();
        jmiRubro = new javax.swing.JMenuItem();
        jmiNombre = new javax.swing.JMenuItem();
        jmiPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout escritorio2Layout = new javax.swing.GroupLayout(escritorio2);
        escritorio2.setLayout(escritorio2Layout);
        escritorio2Layout.setHorizontalGroup(
            escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        escritorio2Layout.setVerticalGroup(
            escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jmAdministracion.setText("Administracion");

        jmiGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/superdetodosa/iconos/icons8-carrito-de-compras-48.png"))); // NOI18N
        jmiGestion.setText("Gestion de Productos");
        jmiGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmiGestion);

        jMenuBar1.add(jmAdministracion);

        jmConsulta.setText("Consulta");
        jmConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaActionPerformed(evt);
            }
        });

        jmiRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/superdetodosa/iconos/icons8-carrito-de-compras-48.png"))); // NOI18N
        jmiRubro.setText("Por Rubro...");
        jmiRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRubroActionPerformed(evt);
            }
        });
        jmConsulta.add(jmiRubro);

        jmiNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/superdetodosa/iconos/icons8-carrito-de-compras-48.png"))); // NOI18N
        jmiNombre.setText("Por Nombre...");
        jmiNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNombreActionPerformed(evt);
            }
        });
        jmConsulta.add(jmiNombre);

        jmiPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/superdetodosa/iconos/icons8-carrito-de-compras-48.png"))); // NOI18N
        jmiPrecio.setText("Por Precio...");
        jmiPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrecioActionPerformed(evt);
            }
        });
        jmConsulta.add(jmiPrecio);

        jMenuBar1.add(jmConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionActionPerformed
      escritorio2.removeAll();
      escritorio2.repaint();
      GestionDeProductos gdp=new GestionDeProductos();
      gdp.setVisible(true);
      escritorio2.add(gdp);
      escritorio2.moveToFront(gdp);
// TODO add your handling code here:
    }//GEN-LAST:event_jmiGestionActionPerformed

    private void jmiRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRubroActionPerformed
        escritorio2.removeAll();
      escritorio2.repaint();
      PorRubro pr=new PorRubro();
      pr.setVisible(true);
      escritorio2.add(pr);
      escritorio2.moveToFront(pr);
    }//GEN-LAST:event_jmiRubroActionPerformed

    private void jmConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmConsultaActionPerformed

    private void jmiNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNombreActionPerformed
      escritorio2.removeAll();
      escritorio2.repaint();
      PorNombre pn=new PorNombre();
      pn.setVisible(true);
      escritorio2.add(pn);
      escritorio2.moveToFront(pn);
    }//GEN-LAST:event_jmiNombreActionPerformed

    private void jmiPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrecioActionPerformed
      escritorio2.removeAll();
      escritorio2.repaint();
      PorPrecio pp=new PorPrecio();
      pp.setVisible(true);
      escritorio2.add(pp);
      escritorio2.moveToFront(pp);
    }//GEN-LAST:event_jmiPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmConsulta;
    private javax.swing.JMenuItem jmiGestion;
    private javax.swing.JMenuItem jmiNombre;
    private javax.swing.JMenuItem jmiPrecio;
    private javax.swing.JMenuItem jmiRubro;
    // End of variables declaration//GEN-END:variables
}
